<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('personal', function (Blueprint $table) {
            $table->integer('PER_COD')->nullable();
            $table->char('PER_NOM', 50)->nullable();
            $table->integer('PER_LEG')->nullable();
            $table->char('PER_AOP', 1)->nullable();
            $table->smallInteger('PER_CON')->nullable();
            $table->dateTime('PER_FNA')->nullable();
            $table->char('PER_LNA', 50)->nullable();
            $table->smallInteger('PER_TD')->nullable();
            $table->char('PER_TDO', 3)->nullable();
            $table->bigInteger('PER_NDO')->nullable();
            $table->char('PER_CUI', 13)->nullable();
            $table->char('PER_DOM', 50)->nullable();
            $table->char('PER_TEL', 50)->nullable();
            $table->char('PER_CEL', 50)->nullable();
            $table->string('PER_CONTACTO', 50)->nullable();
            $table->boolean('AFJP')->nullable();
            $table->boolean('REPARTO')->nullable();
            $table->char('DESCSISTEM', 100)->nullable();
            $table->char('OBRASOCIAL', 50)->nullable();
            $table->boolean('JUBILACION')->nullable();
            $table->boolean('SUBSIDIOS')->nullable();
            $table->char('DESCJUB', 50)->nullable();
            $table->char('DESCSUBS', 50)->nullable();
            $table->char('RESPONSABL', 100)->nullable();
            $table->boolean('ACTIVO')->nullable();
            $table->dateTime('PER_ING')->nullable();
            $table->dateTime('PER_BAJ')->nullable();
            $table->dateTime('HORA')->nullable();
            $table->text('CBU')->nullable();
            $table->char('PER_LOC', 50)->nullable();
            $table->text('PER_OBS')->nullable();
            $table->tinyInteger('PER_EMP')->nullable();
            $table->char('PER_EMD', 30)->nullable();
            $table->char('PER_CDE', 20)->nullable();
            $table->char('PER_APC', 1)->nullable();
            $table->smallInteger('PER_CAT')->nullable();
            $table->char('PER_CAD', 20)->nullable();
            $table->tinyInteger('PER_ANT')->nullable();
            $table->char('PER_JRE', 1)->nullable();
            $table->decimal('PER_SOC', 5, 2)->nullable();
            $table->integer('PER_COS')->nullable();
            $table->tinyInteger('PER_ADE')->nullable();
            $table->tinyInteger('PER_CYG')->nullable();
            $table->smallInteger('PER_PPR')->nullable();
            $table->smallInteger('PER_AOS')->nullable();
            $table->char('PER_JOM', 1)->nullable();
            $table->smallInteger('PER_REB')->nullable();
            $table->tinyInteger('PER_GEO')->nullable();
            $table->smallInteger('PER_ACT')->nullable();
            $table->tinyInteger('PER_RED')->nullable();
            $table->char('PER_SIN', 1)->nullable();
            $table->char('PER_PSN', 1)->nullable();
            $table->tinyInteger('PER_ESP')->nullable();
            $table->tinyInteger('PER_HIJ')->nullable();
            $table->tinyInteger('PER_HIM')->nullable();
            $table->tinyInteger('PER_HID')->nullable();
            $table->tinyInteger('PER_EPR')->nullable();
            $table->tinyInteger('PER_EMS')->nullable();
            $table->tinyInteger('PER_FNU')->nullable();
            $table->decimal('PER_AEP', 8, 2)->nullable();
            $table->tinyInteger('PER_PRE')->nullable();
            $table->tinyInteger('PER_CAS')->nullable();
            $table->tinyInteger('PER_NAS')->nullable();
            $table->smallInteger('PER_ADO')->nullable();
            $table->smallInteger('PER_OC1')->nullable();
            $table->char('PER_NO1', 20)->nullable();
            $table->decimal('PER_OT1', 8, 2)->nullable();
            $table->smallInteger('PER_OC2')->nullable();
            $table->char('PER_NO2', 20)->nullable();
            $table->decimal('PER_OT2', 8, 2)->nullable();
            $table->smallInteger('PER_OC3')->nullable();
            $table->char('PER_NO3', 20)->nullable();
            $table->decimal('PER_OT3', 8, 2)->nullable();
            $table->smallInteger('PER_OC4')->nullable();
            $table->char('PER_NO4', 20)->nullable();
            $table->decimal('PER_OT4', 8, 2)->nullable();
            $table->smallInteger('PER_OC5')->nullable();
            $table->char('PER_NO5', 20)->nullable();
            $table->decimal('PER_OT5', 8, 2)->nullable();
            $table->decimal('PER_PRO', 8, 2)->nullable();
            $table->decimal('PER_PLU', 8, 2)->nullable();
            $table->decimal('PER_HE5', 10, 2)->nullable();
            $table->decimal('PER_HE1', 10, 2)->nullable();
            $table->decimal('PER_PPS', 10, 2)->nullable();
            $table->dateTime('PER_PFD')->nullable();
            $table->dateTime('PER_PFH')->nullable();
            $table->char('PER_PO1', 50)->nullable();
            $table->char('PER_PO2', 50)->nullable();
            $table->char('PER_PO3', 50)->nullable();
            $table->char('PER_PO4', 50)->nullable();
            $table->decimal('PER_PRM', 10, 2)->nullable();
            $table->decimal('PER_JUB', 5, 2)->nullable();
            $table->char('PER_OB2', 50)->nullable();
            $table->decimal('PER_OSO', 5, 2)->nullable();
            $table->char('PER_ALM', 1)->nullable();
            $table->decimal('PER_SUE', 12, 2)->nullable();
            $table->char('PER_CHE', 1)->nullable();
            $table->smallInteger('PER_HEN')->nullable();
            $table->smallInteger('PER_HSA')->nullable();
            $table->tinyInteger('PER_ECI')->nullable();
            $table->char('PER_CBU', 30)->nullable();
            $table->char('PER_HOB', 100)->nullable();
            $table->char('PER_PMP', 50)->nullable();
            $table->dateTime('PER_FAS')->nullable();
            $table->char('PER_NES', 100)->nullable();
            $table->char('PER_CPA', 15)->nullable();
            $table->char('PER_LIC', 1)->nullable();
            $table->char('PER_LCA', 15)->nullable();
            $table->dateTime('PER_LVE')->nullable();
            $table->bigInteger('PER_CONTRA')->nullable();
            $table->bigInteger('PER_LUGAR')->nullable();
            $table->char('PER_JSN', 1)->nullable();
            $table->char('PER_LN1', 12)->nullable();
            $table->char('PER_LC1', 4)->nullable();
            $table->dateTime('PER_LF1')->nullable();
            $table->char('PER_LN2', 12)->nullable();
            $table->char('PER_LC2', 4)->nullable();
            $table->dateTime('PER_LF2')->nullable();
            $table->char('PER_LN3', 12)->nullable();
            $table->char('PER_LC3', 4)->nullable();
            $table->dateTime('PER_LF3')->nullable();
            $table->char('PER_LSF', 1)->nullable();
            $table->char('PER_LSG', 1)->nullable();
            $table->char('PER_LDO', 1)->nullable();
            $table->char('PER_LOB', 40)->nullable();
            $table->char('PER_LRE', 40)->nullable();
            $table->char('PER_LCD', 40)->nullable();
            $table->decimal('PER_REMU', 12, 2)->nullable();
            $table->decimal('PER_NREM', 12, 2)->nullable();
            $table->char('PER_CAR', 1)->nullable();
            $table->dateTime('PER_CAA')->nullable();
            $table->decimal('PER_JRC', 8, 4)->nullable();
            $table->smallInteger('PER_BAN')->nullable();
            $table->char('PER_BAD', 50)->nullable();
            $table->tinyInteger('PER_COMN')->nullable();
            $table->char('PER_COMD', 50)->nullable();
            $table->decimal('PER_ANTI', 10, 2)->nullable();
            $table->decimal('PER_FUTAUT', 12, 2)->nullable();
            $table->decimal('PER_50', 12, 2)->nullable();
            $table->decimal('PER_100', 12, 2)->nullable();
            $table->decimal('PER_NOC', 12, 2)->nullable();
            $table->decimal('PER_VIA', 12, 2)->nullable();
            $table->tinyInteger('PER_SEC')->nullable();
            $table->string('PER_SED', 50)->nullable();
            $table->smallInteger('PER_HORAS')->nullable();
            $table->integer('PER_GRU')->nullable();
            $table->boolean('PARTE_ENV')->nullable();
            $table->tinyInteger('PARTE_PRG')->nullable();
            $table->smallInteger('PER_SUC')->nullable();
            $table->char('PER_SUD', 30)->nullable();
            $table->smallInteger('PER_BSFSUC')->nullable();
            $table->bigInteger('PER_BSFNRO')->nullable();
            $table->char('PER_BAJ_RAZON', 100)->nullable();
            $table->tinyInteger('PER_MSI')->nullable();
            $table->char('PER_MSD', 50)->nullable();
            $table->decimal('PER_HNORMAL', 5, 2)->nullable();
            $table->decimal('PER_HSABADO', 5, 2)->nullable();
            $table->string('PER_EMBSN', 1)->nullable();
            $table->string('PER_EMBNOM', 30)->nullable();
            $table->string('PER_EMBCBU', 22)->nullable();
            $table->boolean('PER_AFILIADO')->nullable();
            $table->decimal('PER_DESCUENTO', 7, 2)->nullable();
            $table->boolean('PER_NOMARCA')->nullable();
            $table->string('PER_NMRAZON', 100)->nullable();
            $table->string('PER_SEX', 1)->nullable();
            $table->boolean('PER_RENTACAR')->nullable();
            $table->dateTime('PER_FEFECTIVO')->nullable();
            $table->boolean('PENDIENTE_SISTEMA')->nullable();
            $table->text('REQUIERE_SISTEMA')->nullable();
            $table->string('PER_EME', 50)->nullable();
            $table->string('PER_EMA', 30)->nullable();
            $table->string('PER_PADRE', 30)->nullable();
            $table->string('PER_MADRE', 30)->nullable();
            $table->string('PER_FACAD', 100)->nullable();
            $table->boolean('PER_ADI_ENC')->nullable();
            $table->boolean('PER_ADI_SUS')->nullable();
            $table->boolean('PER_TIENEPC')->nullable();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('personal');
    }
};
